### ISSUE TITLE
WBD watershed access using pynhd.WaterData vs pygeoogc.ArcGISRESTful

### ISSUE THREAD

**Issue by emiliom** [cheginit/pynhd#1]
Currently we can get WBD data using either `pynhd.WaterData` or `pygeoogc.ArcGISRESTful().restful.wbd`. The former accesses the USGS "waterlabs" GeoServer (which presumably is more experimental and less publicly supported) and the latter apparently accesses the official USGS TNM source. The former provides access to HUC08 and HUC12 layers, while the latter apparently only provides access to a HUC12 layer -- at least that's what I see in [your pygeoogc example](https://github.com/cheginit/pygeoogc/blob/master/README.rst).

Which one would you recommend to a new user of the `hydrodata` ecosystem? I think that choice is somewhat confusing to users unfamiliar with web services. Personally, I like having the option to access a HUC08 layer directly, but at the same time the projection inconsistencies in the waterlabs Geoserver layers are not user friendly.

For WaterHackWeek I'm using `pynhd.WaterData` exclusively. FYI, here's the current state of [my WHW tutorial notebook](https://github.com/waterhackweek/waterdata/blob/master/mashup_waterbudget.ipynb) that uses the hydrodata suite to query for HUC layers. It's almost done, but it'll continue to change for the next couple of days.

**Comment by cheginit** [comment]
As you said, it really depends on the data that you need. The reason that I added the ArcGIS service is that it has all the HUCs, not just 8 and 12. I think that `WaterData` is more intended as complementary data for NHDPlus. If someone is only interested in WBD then the ArcGIS service is the way to go, but if you want to work with NHDPlus you can get them from `WaterData` and not bother with a separate function for using the ArcGIS-based service. I didn't find any projection inconsistencies, can you provide an example?

I looked at the notebook. It's a good tutorial. I have a few comments about the code that I will add to your repository.

**Comment by emiliom** [comment]
For the ArcGIS WBD service, I realize now that the different HUC resolutions are available via the "id" at the end of the url, like this:
- HUC14: https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/7
- HUC10: https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/5
- HUC06: https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/3

and so on. That wasn't clear from your example at https://github.com/cheginit/pygeoogc/blob/master/README.rst, but going directly to https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer, it becomes clear.

The projection inconsistency is on the `pynhd.WaterData` layers, and it's what I described via email with you, Jim and Dave last month:

> In testing its access to your GeoServer, I see some inconsistencies, confusing or annoyances around what projections are supported and what it's doing in the responses. The featuretypes in the WFS GetCapabilities have DefaultSRS values of either epsg 4269 or 900913 (old code web mercator; 3857 is the preferred value these days). It's 900913 for both huc8 and huc12 featuretypes. But the following WFS GetFeature requests return different things:
>
> For both requests, the common part of the request url is this:
> https://labs.waterdata.usgs.gov/geoserver/wmadata/ows?service=wfs&version=1.1.0&outputFormat=application%2Fjson&request=GetFeature
>
> huc08 request: `&typeName=wmadata:huc08&cql_filter=wmadata:huc8 = '17030001'`
> returns a GeoJSON with a crs property of `urn:ogc:def:crs:EPSG::900913`, and the coordinate values appear to be in 900913 as well.
>
> huc12 request:
> `&typeName=wmadata:huc12&cql_filter=wmadata:huc12 LIKE '17030001%'`
> returns a GeoJSON with a crs property of `urn:ogc:def:crs:EPSG::900913`, but the coordinate values are in some lat lon (4326?).
Passing a SRSName=epsg:4326 to the latter request leads to corrupted coordinates.

To which you replied:

> Regarding the CRS stuff, I agree. I actually discussed it with Dave the other day and it seems that having a CRS field in GeoJSON is deprecated and it's assumed that the data is in 4326. So I guess there's still some work that needs to be done about standardizing the data releases.

**Comment by cheginit** [comment]
> That wasn't clear from your example at https://github.com/cheginit/pygeoogc/blob/master/README.rst, but going directly to https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer, it becomes clear.

I will add a note to README to make it more clear.

> The projection inconsistency is on the `pynhd.WaterData` layers, and it's what I described via email.

Ah, ok. The one that I mentioned in the email was related to the inconsistencies due to the axis order (xy or yx) that I fixed in the new release. It took some digging up and I ended up adding a new flag `always_xy` to make it more general since WaterData doesn't follow the new common practice for changing the axis order for geographic CRSs. Also, there was an issue with the filter spec version that WaterData uses version 2 so I also added that option as well.

I looked into the example and you're right, the data appears to be in 4269 but CRS property shows 900913. I will talk to WaterData people and ask them to fix it as well as the axis order issue. Thanks!

**Comment by emiliom** [comment]
Now that I know we can access all HUC levels via `pygeoogc.ArcGISRESTful().restful.wbd`, I'm now thinking that in my tutorial it may be simpler to use that for WBD access. We'll see. Including the `cql_filter` hack in my tutorial is not great.

**Comment by cheginit** [comment]
That's great. I agree it might make things a little complicated for beginners. I might steal it for the package though!

You can make the tutorial even simpler by using PyDaymet since it takes care of some of the intermediate steps that you're doing in the tutorial!

BTW, PyGeoUtils has a utility for masking xarray data called [`xarray_geomask`](https://github.com/cheginit/pygeoutils).

**Comment by emiliom** [comment]
> I might steal it for the package though!

Absolutely. I meant to submit a PR but haven't gotten around to it.

> You can make the tutorial even simpler by using PyDaymet since it takes care of some of the intermediate steps that you're doing in the tutorial!

Right, but the tutorial is not about Daymet per se, and the goal is not necessarily to make everything super simple. It is to convey useful and common approaches. So, I like having the rioxarray reprojection steps in there. They'll be of wider use beyond Daymet.

> BTW, PyGeoUtils has a utility for masking xarray data called xarray_geomask.

Thanks. I'll stick with regionmask, though. For masking purposes, it's a much more widely used, known and supported package.

**Comment by emiliom** [comment]
Regarding the `cql_filter` functionality: I've generalized my function to a form that is closer to what you may want to code into pygeoogc/pygeoutils:

```python
def wfs_getfeatures_cqlfilter(wd, cql_filter=None):
    payload = {
        "service": "wfs",
        "request": "GetFeature",
        "version": wd.version,
        "outputFormat": wd.outformat,
        "typeName": wd.layer,
    }
    if type(cql_filter) is str:
        payload["cql_filter"] = cql_filter

    r = geoogc.RetrySession().get(wd.url, payload)
    
    return geoutils.json2geodf(r.json(), "epsg:4326", crs="epsg:4326")
```

And a sample call:

```python
uy_huc08code = '17030001'
uy_wdhuc12 = pynhd.WaterData('huc12', crs='epsg:900913')
uy_huc12_gdf = wfs_getfeatures_cqlfilter(
    uy_wdhuc12, 
    cql_filter=f"huc12 LIKE '{uy_huc08code}%'"
)
```

CQL & ECQL: https://docs.geoserver.org/latest/en/user/tutorials/cql/cql_tutorial.html

**Comment by cheginit** [comment]
Thanks! I have already added a new function to PyGeoOGC for CQL. [Here](https://github.com/cheginit/pygeoogc/commit/edf31424a91f29d7b2a29f45a961f15f0d6fc24b) is the commit.

**Comment by emiliom** [comment]
Awesome!
