### ISSUE TITLE
WaterData.byid vs WaterData.getfeature_byid

### ISSUE THREAD

**Issue by emiliom** [cheginit/pynhd#2]
Two methods provided by the `WaterData` class are largely equivalent: `byid` and `getfeature_byid`. `getfeature_byid` appears to be inherited from `pygeoogc.WFS` and is lower-level compared to `byid`. `byid`is a lot more convenient b/c it returns a GeoDataFrame.

But `byid` doesn't have a docstring, so it's not obvious how it's used and how it's different from `getfeature_byid`. Assuming I'm getting this right (FYI, I settled on using `byid` b/c it's a lot more convenient), I suggest at least adding a docstring to `byid`. I can submit a PR later, once you confirm I *am* getting this right.

**Comment by cheginit** [comment]
Thanks for the report. As you pointed out `WaterData` is based on `WFS` so all the lower methods are there. There are two functions that are intended to be used with `WaterData`, `byid` and `bybox`. I will add a comment in the docstring.

**Comment by cheginit** [comment]
I cleaned up the `WaterData` class and now it only has four methods: `byid`, `bybox`, `byfilter`, and `to_geodf`.
