### ISSUE TITLE
Example notebook import errors

### ISSUE THREAD

**Issue by jjstarn-usgs** [cheginit/pynhd#30]
I am trying to use the example Jupyter Notebook for PyNHD.

After commenting out the import of a colormap that isn't present:

![image](https://user-images.githubusercontent.com/6577137/131908480-7a018991-9563-42f1-b7a9-1777371b6db6.png)

If I change the import of pynhd to pynhd.pynhd,  I get the following message:

![image](https://user-images.githubusercontent.com/6577137/131908628-0a805d14-83ed-4502-b192-4a14440ca7fb.png)

**Comment by cheginit** [comment]
Can you please let me know how did you install `pynhd`?

**Comment by jjstarn-usgs** [comment]
Thanks for getting back to me.  I look forward to using your software.

I originally had installed pynhd by placing the repo clone in my path.

Today I installed pynhd from conda-forge.  I am getting a different message now.

[cid:11f7d6af-c8c0-49ad-816f-f922e30e8c27]

Jon Jeffrey Starn Ph.D.
Research hydrologist
USGS New England Water Science Center
101 Pitkin Street
East Hartford, CT 06108
________________________________
From: Taher Chegini ***@***.***>
Sent: Thursday, September 2, 2021 5:06 PM
To: cheginit/pynhd ***@***.***>
Cc: Starn, Jeffrey ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [cheginit/pynhd] Example notebook import errors (#30)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Can you please let me know how did you install pynhd?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcheginit%2Fpynhd%2Fissues%2F30%23issuecomment-912057190&data=04%7C01%7Cjjstarn%40usgs.gov%7C336d4a0df0264b761bff08d96e55b1ac%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637662136610181165%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YhFAqN%2BVVghHr2Tskvu4lWhjZU9JUc9TR3waAKSbjNw%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABSFX4JMUZXHS6L5UP5ZPUTT77RO5ANCNFSM5DJ3NBHQ&data=04%7C01%7Cjjstarn%40usgs.gov%7C336d4a0df0264b761bff08d96e55b1ac%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637662136610191127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BT55YkwCsI1BK0%2Fcf%2BzFG%2BZqPs4AmaIYe1WE8OmkPhQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjjstarn%40usgs.gov%7C336d4a0df0264b761bff08d96e55b1ac%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637662136610191127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=X5PGtHq5yKLXoQXlh1GYckHEO11W7Esq3w48fYAegls%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjjstarn%40usgs.gov%7C336d4a0df0264b761bff08d96e55b1ac%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637662136610201076%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kp2Rmwbt0gI0ARk%2BE92aSCi4Zj%2BQFk3tFJDGyyWje2Y%3D&reserved=0>.

**Comment by cheginit** [comment]
Sure!

The image that you attached is not showing up on Github, can you please resend it so I can see the error message?

**Comment by jjstarn-usgs** [comment]
Hope this works better...

[cid:76f941a5-fa63-41ea-96f7-7ccad703f245]

Jon Jeffrey Starn Ph.D.
Research hydrologist
USGS New England Water Science Center
101 Pitkin Street
East Hartford, CT 06108
________________________________
From: Taher Chegini ***@***.***>
Sent: Tuesday, September 14, 2021 10:52 AM
To: cheginit/pynhd ***@***.***>
Cc: Starn, Jeffrey ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [cheginit/pynhd] Example notebook import errors (#30)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Sure!

The image that you attached is not showing up on Github, can you please resend it so I can see the error message?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcheginit%2Fpynhd%2Fissues%2F30%23issuecomment-919227471&data=04%7C01%7Cjjstarn%40usgs.gov%7C74947ea17875471dcc5608d9778f42aa%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637672279453436616%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5BRhypZ%2Fwq65BulIwectbSk8%2FYSS1zQ61vo8w25W5Bk%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABSFX4NW7SH4HAUPICOQF5TUB5ORTANCNFSM5DJ3NBHQ&data=04%7C01%7Cjjstarn%40usgs.gov%7C74947ea17875471dcc5608d9778f42aa%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637672279453446583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pK0675nqPqYTfDVFRncWX0HZ9WWymu8RHnjtQukzqTg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjjstarn%40usgs.gov%7C74947ea17875471dcc5608d9778f42aa%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637672279453446583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OnY2UZqU2ODMQMWbaey9VJdTbDMDn1c8Ste%2F4XYk1Bg%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjjstarn%40usgs.gov%7C74947ea17875471dcc5608d9778f42aa%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637672279453446583%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=o7TffvCMbLTsjUKrWcKCRegzloP%2F7I73ET2FgSpY%2F2Q%3D&reserved=0>.

**Comment by cheginit** [comment]
Still not showing up. I thought since you're replying from your email it doesn't show up here but I also checked it via email and it just shows this:

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/13016644/133288399-c45f8f93-5e6e-4fd2-9e7e-524cd2b4b8b4.png">

I think you need to attach it as an image rather than pasting from clipboard.

**Comment by jjstarn-usgs** [comment]
Thank you, pynhd_example.ipynb worked great once I installed the correct environment.

Jon Jeffrey Starn Ph.D.
Research hydrologist
USGS New England Water Science Center
101 Pitkin Street
East Hartford, CT 06108
________________________________
From: Taher Chegini ***@***.***>
Sent: Tuesday, September 14, 2021 12:06 PM
To: cheginit/pynhd ***@***.***>
Cc: Starn, Jeffrey ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [cheginit/pynhd] Example notebook import errors (#30)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



No problem.

The best way to install it is to create a new environment using conda (or mambaforge<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fconda-forge%2Fminiforge&data=04%7C01%7Cjjstarn%40usgs.gov%7Cc1db74086a594fad2a0808d97799d78f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637672324912375533%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3thdO4OQpkzNhZgol0ipF6ZgIQkyoGWF1VNFzX8YGrY%3D&reserved=0>) and this<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcheginit%2FHyRiver-examples%2Fblob%2Fmain%2Fenvironment.yml&data=04%7C01%7Cjjstarn%40usgs.gov%7Cc1db74086a594fad2a0808d97799d78f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637672324912385492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MxQvh01xG8c9ynN0oOOnhjnXplL0PcjMk1pdb4Bg8pI%3D&reserved=0> env file. Just download the file, make changes if needed (for example, change the name to your liking and add or remove packages), and do the following:

conda env create -f environment.yml

You can then activate the environment and start coding!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcheginit%2Fpynhd%2Fissues%2F30%23issuecomment-919295005&data=04%7C01%7Cjjstarn%40usgs.gov%7Cc1db74086a594fad2a0808d97799d78f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637672324912385492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gBIg2ztmXw%2FmvSvmYifogw00SwYfkS7zlOkptjmQ%2B94%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABSFX4OHOP7DFDI5MIRXH7DUB5XHFANCNFSM5DJ3NBHQ&data=04%7C01%7Cjjstarn%40usgs.gov%7Cc1db74086a594fad2a0808d97799d78f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637672324912395451%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KcoC0JuV%2FKUzImMRgpguEKXS%2BLkRJ1BvfXzuqQP3xsg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjjstarn%40usgs.gov%7Cc1db74086a594fad2a0808d97799d78f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637672324912395451%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TUc7HrDTbZxPFURhNKyg8rltlK%2FYY7LNkGtZ4gEPhZM%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjjstarn%40usgs.gov%7Cc1db74086a594fad2a0808d97799d78f%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637672324912395451%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=P3%2Fdka%2FkgexfggaFD3DYua4r2BpDlf2wnVJGJFbgmTw%3D&reserved=0>.

**Comment by cheginit** [comment]
Great, glad it worked! I'll close the issue. Please free to re-open if you have any other questions.
